# Usa la imagen oficial de Nginx como base
FROM nginx:latest

# Copia los archivos estáticos al directorio de trabajo de Nginx
COPY ./ /usr/share/nginx/html/juegos/

# Expone el puerto 80 para que puedas acceder a tu aplicación desde el navegador
EXPOSE 80